name: money_laundry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/images/logo.png
    - ./assets/images/order.jpg
    - ./assets/images/listorder.jpg
    - ./assets/images/report.jpg
    - ./assets/images/service.jpg

flutter_native_splash:
  color: "#215C87"
  image_dark: ./assets/images/logo.png
  android: true
  ios: true